#!/bin/bash
# Generated by Baryon transpiler
set -euo pipefail
IFS=$'\n\t'
trap 'echo "Error on line $LINENO" >&2' ERR

# Utility functions
log_info() { echo "[INFO] $*" >&2; }
log_error() { echo "[ERROR] $*" >&2; }

check_docker() {
  if ! command -v docker &> /dev/null; then
    log_error "Docker is not installed or not in PATH."
    exit 1
  fi
}

run_docker() {
  local image="$1"; shift
  local opts=()
  while [[ $# -gt 0 && "$1" != "--" ]]; do
    opts+=("$1"); shift
  done
  [[ "$1" == "--" ]] && shift
  log_info "Running Docker image: $image"
  docker run --rm "${opts[@]}" "$image" "$@"
}

# Argument parsing
usage() {
  echo "Usage: $0 [options]"
  echo "  --target_directory <value>"
  echo "  --script_directory <value>"
  echo "  --guide_strategy <value>"
  echo "  --matrix_filename <value>"
  echo "  --threshold_a <value>"
  echo "  --threshold_i <value>"
  exit 1
}

# Initialize variables
target_directory=""
script_directory=""
guide_strategy=""
matrix_filename=""
threshold_a=""
threshold_i=""

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    --target_directory)
      target_directory="$2"
      shift
      shift
    ;;
    --script_directory)
      script_directory="$2"
      shift
      shift
    ;;
    --guide_strategy)
      guide_strategy="$2"
      shift
      shift
    ;;
    --matrix_filename)
      matrix_filename="$2"
      shift
      shift
    ;;
    --threshold_a)
      threshold_a="$2"
      shift
      shift
    ;;
    --threshold_i)
      threshold_i="$2"
      shift
      shift
    ;;
    -h|--help)
      usage
    ;;
    *)
      log_error "Unknown option: $1"
      usage
    ;;
  esac
done

if [[ ! -d "$target_directory" ]]; then
  echo "Error: target_directory must be a valid directory" >&2
  exit 1
fi
if [[ ! -d "$script_directory" ]]; then
  echo "Error: script_directory must be a valid directory" >&2
  exit 1
fi
if [[ ! "${guide_strategy}" =~ ^("1"|"2")$ ]]; then
  echo "Error: guide_strategy must be one of: "1", "2"" >&2
  exit 1
fi
if [[ -z "$matrix_filename" ]]; then
  echo "Error: matrix_filename must be a non-empty string" >&2
  exit 1
fi
if [[ -z "$threshold_a" ]]; then
  echo "Error: threshold_a must be a non-empty string" >&2
  exit 1
fi
if [[ -z "$threshold_i" ]]; then
  echo "Error: threshold_i must be a non-empty string" >&2
  exit 1
fi

# Process file paths for Docker
target_directory_abspath=$(cd "$(dirname "$target_directory")" && pwd)/$(basename "$target_directory")
target_directory_dir=$(dirname "$target_directory_abspath")
target_directory_filename=$(basename "$target_directory_abspath")
script_directory_abspath=$(cd "$(dirname "$script_directory")" && pwd)/$(basename "$script_directory")
script_directory_dir=$(dirname "$script_directory_abspath")
script_directory_filename=$(basename "$script_directory_abspath")

check_docker

# Run Docker container
docker_opts=()
docker_opts+=(-v "$target_directory_dir:/mnt/analysis")
docker_opts+=(-v "$script_directory_dir:/opt/scripts")
container_args=()
container_args+=("/opt/scripts/CIRI_unified.R")
container_args+=("/mnt/analysis")
container_args+=("$guide_strategy")
container_args+=("$matrix_filename")
container_args+=("$threshold_a")
container_args+=("$threshold_i")
run_docker "docker.io/hedgelab/ciri_analysis" "${docker_opts[@]}" -- "${container_args[@]}"
