#!/bin/bash
# Generated by Baryon transpiler
set -euo pipefail
IFS=$'\n\t'
trap 'echo "Error on line $LINENO" >&2' ERR

# Utility functions
log_info() { echo "[INFO] $*" >&2; }
log_error() { echo "[ERROR] $*" >&2; }

check_docker() {
  if ! command -v docker &> /dev/null; then
    log_error "Docker is not installed or not in PATH."
    exit 1
  fi
}

run_docker() {
  local image="$1"; shift
  local opts=()
  while [[ $# -gt 0 && "$1" != "--" ]]; do
    opts+=("$1"); shift
  done
  [[ "$1" == "--" ]] && shift
  log_info "Running Docker image: $image"
  docker run --rm "${opts[@]}" "$image" "$@"
}

# Argument parsing
usage() {
  echo "Usage: $0 [options]"
  echo "  --scripts_dir <value>"
  echo "  --data_dir <value>"
  echo "  --mode <value>"
  exit 1
}

# Initialize variables
scripts_dir=""
data_dir=""
mode=""

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    --scripts_dir)
      scripts_dir="$2"
      shift
      shift
    ;;
    --data_dir)
      data_dir="$2"
      shift
      shift
    ;;
    --mode)
      mode="$2"
      shift
      shift
    ;;
    -h|--help)
      usage
    ;;
    *)
      log_error "Unknown option: $1"
      usage
    ;;
  esac
done

if [[ ! -d "$scripts_dir" ]]; then
  echo "Error: scripts_dir must be a valid directory" >&2
  exit 1
fi
if [[ ! -d "$data_dir" ]]; then
  echo "Error: data_dir must be a valid directory" >&2
  exit 1
fi
if [[ ! "${mode}" =~ ^("1"|"2")$ ]]; then
  echo "Error: mode must be one of: "1", "2"" >&2
  exit 1
fi

# Process file paths for Docker
scripts_dir_abspath=$(cd "$(dirname "$scripts_dir")" && pwd)/$(basename "$scripts_dir")
scripts_dir_dir=$(dirname "$scripts_dir_abspath")
scripts_dir_filename=$(basename "$scripts_dir_abspath")
data_dir_abspath=$(cd "$(dirname "$data_dir")" && pwd)/$(basename "$data_dir")
data_dir_dir=$(dirname "$data_dir_abspath")
data_dir_filename=$(basename "$data_dir_abspath")

check_docker

# Run Docker container
docker_opts=()
docker_opts+=(-v "$scripts_dir_dir:/scripts")
docker_opts+=(-v "$data_dir_dir:/data")
container_args=()
container_args+=("Rscript")
container_args+=("/scripts/CIRI_unified.R")
container_args+=("/data")
container_args+=("$mode")
run_docker "docker.io/hedgelab/ciri_analysis" "${docker_opts[@]}" -- "${container_args[@]}"
